### ISSUE TITLE
syntax error on keyboard_helper.rb

### ISSUE THREAD

**Issue by lukapril** [moredip/Frank#101]
There's an extra comma on line 9 of the keyboard_helper.rb file, hence giving error when i attempt to run a frank-cucumber script. Below is the error from console:

/Users/localuser/.rvm/gems/ruby-1.8.7-p358/gems/frank-cucumber-0.8.14/lib/frank-cucumber/keyboard_helper.rb:10: syntax error, unexpected ')' (SyntaxError)
/Users/localuser/.rvm/rubies/ruby-1.8.7-p358/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:55:in `gem_original_require'
/Users/localuser/.rvm/rubies/ruby-1.8.7-p358/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:55:in`require'
/Users/localuser/.rvm/gems/ruby-1.8.7-p358/gems/frank-cucumber-0.8.14/lib/frank-cucumber/frank_helper.rb:5
/Users/localuser/.rvm/rubies/ruby-1.8.7-p358/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:55:in `gem_original_require'
/Users/localuser/.rvm/rubies/ruby-1.8.7-p358/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:55:in`require'
/Users/localuser/.rvm/gems/ruby-1.8.7-p358/gems/frank-cucumber-0.8.14/lib/frank-cucumber.rb:2
/Users/localuser/.rvm/rubies/ruby-1.8.7-p358/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:60:in `gem_original_require'
/Users/localuser/.rvm/rubies/ruby-1.8.7-p358/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:60:in`require'
/Users/localuser/apps/beaucoo-iphone-app/Frank/features/support/env.rb:1
/Users/localuser/.rvm/gems/ruby-1.8.7-p358/gems/cucumber-1.2.0/bin/../lib/cucumber/rb_support/rb_language.rb:129:in `load'
/Users/localuser/.rvm/gems/ruby-1.8.7-p358/gems/cucumber-1.2.0/bin/../lib/cucumber/rb_support/rb_language.rb:129:in`load_code_file'
/Users/localuser/.rvm/gems/ruby-1.8.7-p358/gems/cucumber-1.2.0/bin/../lib/cucumber/runtime/support_code.rb:171:in `load_file'
/Users/localuser/.rvm/gems/ruby-1.8.7-p358/gems/cucumber-1.2.0/bin/../lib/cucumber/runtime/support_code.rb:83:in`load_files!'
/Users/localuser/.rvm/gems/ruby-1.8.7-p358/gems/cucumber-1.2.0/bin/../lib/cucumber/runtime/support_code.rb:82:in `each'
/Users/localuser/.rvm/gems/ruby-1.8.7-p358/gems/cucumber-1.2.0/bin/../lib/cucumber/runtime/support_code.rb:82:in`load_files!'
/Users/localuser/.rvm/gems/ruby-1.8.7-p358/gems/cucumber-1.2.0/bin/../lib/cucumber/runtime.rb:175:in `load_step_definitions'
/Users/localuser/.rvm/gems/ruby-1.8.7-p358/gems/cucumber-1.2.0/bin/../lib/cucumber/runtime.rb:40:in`run!'
/Users/localuser/.rvm/gems/ruby-1.8.7-p358/gems/cucumber-1.2.0/bin/../lib/cucumber/cli/main.rb:43:in `execute!'
/Users/localuser/.rvm/gems/ruby-1.8.7-p358/gems/cucumber-1.2.0/bin/../lib/cucumber/cli/main.rb:20:in`execute'
/Users/localuser/.rvm/gems/ruby-1.8.7-p358/gems/cucumber-1.2.0/bin/cucumber:14
/Users/localuser/.rvm/gems/ruby-1.8.7-p358/bin/cucumber:19:in `load'
/Users/localuser/.rvm/gems/ruby-1.8.7-p358/bin/cucumber:19

**Comment by moredip** [comment]
This was fixed in 9d5b0fefb26bbc298f3ff502c65049f5273e65b8

**Comment by lukapril** [comment]
hey Pete, I did a gem update for frank-cucumber and rerun my script and see the same error, any idea?
I'm using frank-cucumber-0.8.14 -Thanks!

**Comment by moredip** [comment]
I haven't cut a new release of the gem. I can do that if you need the fix, or you could do a local build of the gem. To build locally do a `rake install` from the gem subdirectory.

**Comment by lukapril** [comment]
Nice! Thanks for the quick reply, I'll go ahead and do a local build :)
- April
