### ISSUE TITLE
Cannot touch a navigation button in a modal navigation view controller

### ISSUE THREAD

**Issue by frenetisch-applaudierend** [moredip/Frank#102]
When I have a modal navigation view controller with a navigation button "Done", then I cannot touch it using `touch( "button marked:'Done'" )` because `touch()` fails with the following message:

```
some views could not be touched (probably because they are not within the current viewport)
```

It does work however, for non-modal UINavigationControllers.

I investigated a little bit and I found that the problem occurs if I use the `UIModalTransitionStyleCoverVertical` style, but not when using `UIModalTransitionStyleCrossDissolve`. Adding a breakpoint in `- (BOOL) touchPointIfInsideWindow:(CGPoint)point` (UIView+KifAdapter.m) I could see that in fact the point is reported to lie outside the window. Also the superview of the navigation bar (`UILayoutContainerView` IIRC) lies outside of the screen (frame is `{ x = 0.0, y = 480.0, width = 320.0, height = 480.0 }`) but it has an animation set, which I assume transforms the view visually back on the screen.

Also interesting is that the button is in fact touched (as confirmed by a breakpoint in my handler method).

I'm not really sure how this can be fixed, since `- [UIView convertPoint:toView:]` reports the wrong value and I didn't find out how to adjust it properly. For now I use a workaround in the `touch()` function to check if any touch succeeded instead of checking if any touch failed. But this doesn't look like a good solution to me.

```
def touch_lenient( uiquery )
  touch_successes = frankly_map( uiquery, 'touch' )
  raise "could not find anything matching [#{uiquery}] to touch" if touch_successes.empty?
  raise "no views could be touched (probably because they are not within the current viewport)" unless touch_successes.include?(true)
end
```

If anyone has any inputs on how to fix / circumvent this problem I'd be very glad.

**Comment by moredip** [comment]
Hi,

This should like it could be because there is an view transition going on as you are trying to tap the button. Could you try using the `wait_for_nothing_to_be_animating` helper method before calling `touch`?

**Comment by frenetisch-applaudierend** [comment]
Ok, just checked again and this was my fault actually. I incorrectly reset my user interface so that I had some lingering views still on the screen which interfered with Frank. Sorry for bothering you.

Thanks for the hint on `wait_for_nothing_to_be_animating` function, I didn't discover this one yet!
