### ISSUE TITLE
Add armv6 support to libFrank.a

### ISSUE THREAD

**Issue by KingOfBrian** [moredip/Frank#104]
Our app still needs armv6 support, so the distributed .a file doesn't work.   It would be great if it was included.   I would submit a patch, but it's simple enough, just change:

ARCHS = "$(ARCHS_STANDARD_32_BIT)"

to

ARCHS = "$(ARCHS_STANDARD_32_BIT)" armv6

**Comment by moredip** [comment]
I'm gonna sound dumb asking this, but where exactly do I need to make this change? Maybe a pull request would be easier for both of us :P

**Comment by moredip** [comment]
Closing stale issues.
