### ISSUE TITLE
http://www.testingwithfrank.com/ redirect loop.

### ISSUE THREAD

**Issue by mcmurrym** [moredip/Frank#107]

**Comment by dlongmuir** [comment]
Thanks

**Comment by sarahhodne** [comment]
This is still an issue. www.testingwithfrank.com redirects to testingwithfrank.com, which redirects back to www.testingwithfrank.com, and so on and so forth.

**Comment by dlongmuir** [comment]
Thanks again everyone. I've rolled back the changes.
