### ISSUE TITLE
Frank launch fails to bring up the emulator

### ISSUE THREAD

**Issue by sdqali** [moredip/Frank#108]
## Steps to reproduce

In an iPhone project do
1. _frank setup_
2. _frank build_
3. _frank launch_

This shows the following output:

```
LAUNCHING IN THE SIMULATOR...
sh: line 1:  1424 Trace/BPT trap: 5       /Users/sdqali/.rvm/gems/ruby-1.9.3-p194@frank/gems/sim_launcher-0.4.0/lib/sim_launcher/../../native/ios-sim "showsdks" 2>&1
sh: line 1:  1427 Trace/BPT trap: 5       /Users/sdqali/.rvm/gems/ruby-1.9.3-p194@frank/gems/sim_launcher-0.4.0/lib/sim_launcher/../../native/ios-sim "launch" "/Users/sdqali/src/play/2012-Olympics-iOS--iPad-and-iPhone--source-code/2012 Olympics/Frank/frankified_build/Frankified.app" "--sdk" "" "--family" "" "--exit" 2>&1
```

The version of Xcode I am using is _Xcode 4.3.2 Build version 4E2002_

The error seems to be happening because the _xcodebuild_ version I have does not accept the _showsdks_ switch, but accepts _-showsdks_

**Comment by moredip** [comment]
Thanks for reporting this. It's an issue with the build of ios-sim which I'm packaging as part of the SimLauncher gem which Frank uses to launch the app in the simulator.

I'm working on a fix, but for the time being a workaround should be to do this:

```
gem uninstall -Iax sim_launcher
gem install sim_launcher -v 0.3.8
```

Please do let me know if that doesn't help you.

**Comment by gordoncww** [comment]
I was having a simliar issue.  Using the the patch here, https://github.com/moredip/Sim-Launcher/pull/5 and ios-sim from homebrew worked for me.

**Comment by moredip** [comment]
I've resolved this for the time being by having frank-cucumber depend on an older version of the sim_launcher gem. If anyone still sees this please re-open this issue.

**Comment by geoffreym74** [comment]
I seem to be seeing this same issue.  XCode version is 4.3.3 (4E3002).
Gem versions are as follows:

**\* LOCAL GEMS ***

builder (3.0.0)
cucumber (1.2.1)
diff-lcs (1.1.3)
dnssd (2.0)
frank-cucumber (0.9.4)
gherkin (2.11.1)
i18n (0.6.0)
json (1.7.3)
plist (3.1.0)
rack (1.4.1)
rack-protection (1.2.0)
rspec (2.11.0)
rspec-core (2.11.1)
rspec-expectations (2.11.1)
rspec-mocks (2.11.1)
sim_launcher (0.3.8)
sinatra (1.3.2)
thor (0.15.4)
tilt (1.3.3)

Output from "frank launch" is:

```
LAUNCHING IN THE SIMULATOR...
sh: line 1: 78722 Trace/BPT trap: 5       /Library/Ruby/Gems/1.8/gems/sim_launcher-  0.3.8/lib/sim_launcher/../../native/iphonesim "showsdks" 2>&1
sh: line 1: 78725 Trace/BPT trap: 5       /Library/Ruby/Gems/1.8/gems/sim_launcher- 0.3.8/lib/sim_launcher/../../native/iphonesim "launch" "/Users/geoffreym/Documents/projects/2012-Olympics-iOS--iPad-  and-iPhone--source-code/2012 Olympics/Frank/frankified_build/Frankified.app" "" "" 2>&1
```

**Comment by moredip** [comment]
@geoffreym74 can you try updating to the latest frank-cucumber and sim_launcher gems and see if that helps?

**Comment by geoffreym74** [comment]
I have tried with frank-cucumber 0.9.4 and 0.9.5-pre4 and get the same error.  Both appear to depend on sim_launcher 0.3.8.  I think I did try with frank-cumber 0.9.4 and sim_launcher 0.4.3 at one point and got a different error.

**Comment by geoffreym74** [comment]
FYI, this seems to be a problem with XCode 4.3.3 and sim_launcher.  I had the same problem with calabash-ios, and was able to work around it by launching the simulator from XCode and setting the environment variable NO_LAUNCH=1.  I'm not sure if the same option or similar is available with Frank?  The other alternative seems to be downgrading to 4.3.2 or earlier XCode.

**Comment by moredip** [comment]
something like NO_LAUNCH is definitely possible - just modify your app launching step to check for that environment variable and do nothing if it's present.

**Comment by JSegoviax** [comment]
Let me preface this with 'I am very new to this'

So I was experiencing this same issue reported here; Frank Launch failed. I was able to get around this by manually selecting the Frankified app in Xcode and launching it in the simulator (you can follow the steps to do that here http://testingwithfrank.com/faq.html). 

All is fine until you try to run cucumber...Ping Failed!!!!!!

So the workaround kinda hit a snag here. I was able to resolve this by relaunching the frankified app in Xcode while the Ping Failed!!! message was running in my terminal.

Hope this helps somebody out there.

**Comment by iamleeg** [comment]
I'm seeing this too, using Xcode 4.6 and current Frank. My sim-launcher gem is 0.4.6 - the workaround of uninstalling that and installing 0.3.8 no longer works so for other readers it's not worth trying that.

**Comment by SrinivasPeriyasamy** [comment]
I'm got this same error. I just ran through all forum threads related to this issue and tried all suggestions, but nothing worked. Finally, I have noted that I was named my Xcode as "Xcode5"(which is Xcode 5.0.2). Just tried with renaming again to "Xcode" and 'frank launch' works!.. Issue ends with fun, for me.

**Comment by adealmeida** [comment]
I just upgraded to Xcode 5.1 and I'm getting the same error as the original poster. I'm using sim_launcher (0.4.6) and frank-cucumber (1.2.2). Pete, can you look into this again?

**Comment by vburojevic** [comment]
I am having the same issue on Xcode 5.1

EDIT:
Installing a new version of sim launcher resolved the issue:
sudo gem install sim_launcher
