### ISSUE TITLE
Find a way to handle interstitial windows presented by Apps

### ISSUE THREAD

**Issue by vmoore** [moredip/Frank#112]
My app offers the ability to connect using the users' Facebook account.  Clicking the 'Connect using Facebook' button in our app opens a 'window' that overlays over our App.  Currently Symbiote can't see the FB window that is obscures view to our App.  Would this be considered a Web View, an interstitial window within our application (even though it's how we connect to Facebooks API?), or the equivalent of a web 'pop up'.  I'd love to author tests that stay 'in-line' with our application, as opposed to logging into other API's outside of our application.  Just something I wanted to throw on the wish list for future Frank revs.

**Comment by moredip** [comment]
Can you ask about this on the Frank mailing list. You'll hopefully get some help there. http://groups.google.com/group/frank-discuss
