### ISSUE TITLE
rake build broken

### ISSUE THREAD

**Issue by CMTaylor** [moredip/Frank#115]
When I try to do a "rake" build of Frank it builds the .a file just fine, and I can use it. But the build process always ends with this error message:
*\* BUILD SUCCEEDED **

rake aborted!
Don't know how to build task 'copy_bundle'

(See full trace by running task with --trace)

Looking in the rakefile at the definition of copy_bundle, I see:

desc "copy resource bundle into dist dir"
task :copy_bundle do
  cp_r 'frank_static_resources.bundle', 'dist'
end

and the inside call "cp_r" is not defined anywhere.  Should this be defined in the rakefile as another task, or is it some external tool?

**Comment by moredip** [comment]
Thanks for spotting this. It's fixed as of 74a4e4254ec01ff2ffe42620ab5eaac61493becf
