### ISSUE TITLE
Embed and log version numbers in libraries

### ISSUE THREAD

**Issue by dhemery** [moredip/Frank#116]
To aid troubleshooting...
- Embed version information in the Frank and Shelley libraries in a format that supports the Unix what(1) command.
- Write the version information to the log when Frank and Shelley are loaded.

This will make it easier for people to identify what versions of the libraries they are using.  Running `what libFrank.a` and `what libShelley.a` will show the versions of the libraries.  Running `what MyAppExecutable` will show what versions of the libraries are linked into the application.

**Comment by moredip** [comment]
Closing stale issues.

This has been implemented for a while now.
