### ISSUE TITLE
arch: posix_spawnp: osascript: Bad CPU type in executable

### ISSUE THREAD

**Issue by brbulic** [moredip/Frank#124]
All events where interaction with keyboard is required fails on Mountain Lion with the error message:

```
 arch: posix_spawnp: osascript: Bad CPU type in executable
```

Versions prior to Mountain Lion have no issues.

Probable culprit: the /usr/bin/osascript executor for AppleScript is not 32 bit capable, and for interacting with the iOS simulator it must be 32 bit capable, since the Simulator is 32 bit.

Evidence:
In Lion when you write 

```
$ file /usr/bin/osascript
/usr/bin/osascript: Mach-O universal binary with 2 architectures
/usr/bin/osascript (for architecture x86_64):    Mach-O 64-bit executable x86_64
/usr/bin/osascript (for architecture i386):    Mach-O executable i386
```

In ML you get:

```
$ file /usr/bin/osascript
/usr/bin/osascript: Mach-O 64-bit executable x86_64
```

**Comment by moredip** [comment]
There shouldn't be anything in Frank that uses osascript to drive the keyboard at this point. I think if you upgrade to the latest gem this will resolve itself. Let me know if not.
