### ISSUE TITLE
shelley_compat bug with TableViewCell taps

### ISSUE THREAD

**Issue by mfrawley** [moredip/Frank#129]
We had a bug that taps on tableViewCells didn't seem to work with the shelley_compat selector engine. We then confirmed it wasn't our custom tableviews by creating a simple TableView (directly from the Rubymotion tutorial http://rubymotion-tutorial.com/5-tables/) .

We used a custom step defined for test:

Then /^I tap the first cell in table "(.*?)"$/  do |table_name|
    frankly_map( "tableView marked:'#{table_name}' tableViewCell index:0", 'touch')
end

Expected result (and actual with uiquery)
Alert with 'A'

Actual result with shelley:
Alert with 'I'

We tried making requests directly with the Chrome REST client and also using the below flag, and observed the same differences:
Frank::Cucumber::FrankHelper.use_shelley_from_now_on

**Comment by mfrawley** [comment]
Tested with frank-cucumber-0.9.4, we also noticed sluggish detection of manual taps on tableviewcells when Shelley is running in the simulator and on device. Does not occur with UIButton taps.

**Comment by moredip** [comment]
This is a known restriction with Shelley - it selects views based on the order they are in the view hierarchy ,which is sometimes counter-intuitive. I would suggest not using index, and instead selecting with some other approach - selecting the table view cell based on some part of its contents for example.
