### ISSUE TITLE
frankly_step error related to waiting for a navigation bar title

### ISSUE THREAD

**Issue by raid5** [moredip/Frank#13]
The following frankly step appears to be broken:

```
Then /^I wait to see a navigation bar titled "([^\"]*)"$/
```

The error tossed in the console is:

```
undefined method `include' for ["Accounts"]:Array (NoMethodError)
/Users/adam/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/timeout.rb:57:in `timeout'
Tests/Acceptance/features/list_available_accounts.feature:9:in `And I wait to see a navigation bar titled "Accounts"'
```

**Comment by rdegraci** [comment]
What version of Ruby, Cucumber do you have installed?

**Comment by raid5** [comment]
ruby 1.9.2p0 (2010-08-18 revision 29036) [x86_64-darwin10.4.0] via RVM
cucumber 0.10.0

**Comment by dlongmuir** [comment]
Confirmed with a 

diff --git a/example/EmployeeAdmin/features/main.feature b/example/EmployeeAdmin/features/main.feature
index 46b3f74..f13bad4 100644
--- a/example/EmployeeAdmin/features/main.feature
+++ b/example/EmployeeAdmin/features/main.feature
@@ -26,6 +26,7 @@ Scenario: default users should be present after app startup

```
 Scenario: attempting to a new user without supplying any input
     When I touch the Add User button
+    And I wait to see a navigation bar titled "User Profile"
     And I touch the "Save" nav bar button
     Then I should see an alert view saying "Invalid User"
```

the include needs to be an include? like:

```
Then /^I wait to see a navigation bar titled "([^\"]*)"$/ do |expected_mark|
  Timeout::timeout(30) do
    values = frankly_map( 'navigationItemView', 'accessibilityLabel' )
    until values.include?(expected_mark)
      values = frankly_map( 'navigationItemView', 'accessibilityLabel' )
      sleep 0.1
    end
  end
end
```

I see a few more bad include calls in the frankly_steps/core_frank_steps. I'll talk to Pete or fix and send a pull request tonight.

Derek.

**Comment by raid5** [comment]
@dlongmuir ahhh, thanks!! I didn't even notice the missing '?' for the `include` method. I'll be watching for this fix, thanks!

**Comment by moredip** [comment]
Derek/Adam, if you have time can you fix core_frank_steps.rb and send me a pull request?

**Comment by dlongmuir** [comment]
I'm almost done with one for the gemify branch

**Comment by moredip** [comment]
Pulled in your fix, this should be resolved now.

**Comment by raid5** [comment]
Excellent. Does that mean there is a new version of the gem and we just need to update?

**Comment by moredip** [comment]
yes, gem version 0.5.4
