### ISSUE TITLE
I got a list of button have the same label any updates about touch button with label and index?

### ISSUE THREAD

**Issue by shoucal** [moredip/Frank#130]
I got a list of button have the same label any updates about touch button with label and index?

because I　want to touch the button that I want. so please give me some help about that.

when I use touch method I can't touch the button which I want to .
please help me about that.

**Comment by moredip** [comment]
Hi,  

Please use the Frank mailing list for general Frank support questions like this - you'll likely get a better response from the community at large.

Cheers,
Pete

**Comment by moredip** [comment]
Sorry, it would have helped if I gave you a pointer to where the Frank discussion list is! It's at http://groups.google.com/group/frank-discuss
