### ISSUE TITLE
"frank setup" doesn't create a runnable app

### ISSUE THREAD

**Issue by undees** [moredip/Frank#137]
Steps to reproduce:

```
git clone git://github.com/sonnyfazio/SignPlus.git
cd SignPlus
open DisplayBoard.xcodeproject
# Build and run manually in Xcode; works fine
frank setup
# ...
/Users/undees/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/frank-cucumber-1.0.0.pre2/lib/frank-cucumber/frankifier.rb:78:in `add_frank_entry_to_build_setting': undefined method `[]' for nil:NilClass (NoMethodError)
```

Adding a line to the end of `build_settings_to_exit`, just to get past the error message:

``` ruby
def build_settings_to_edit
  @_build_settings_to_edit ||= @target.build_configuration_list.build_settings(@target_build_configuration)
  @_build_settings_to_edit ||= Hash.new { |k, v| [] }
end
```

Continuing:

```
frank setup
frank launch --idiom=ipad
```

The simulator launches, but the screen just stays blank, as if the app has hung. Running `frank inspect` opens the browser, but the app doesn't appear to be listening on the port.

This is an older project, so this may be an Xcode project structure that won't work with the xcodeproejct gem used by Frank.

**Comment by moredip** [comment]
First part of this was fixed by 9f38ef5600d9cf34ae54ae1b456e69426c7df9a4
Second issue was fixed by 0a15c2f85bd30e38c3d1fe13c26caaa40607b153
