### ISSUE TITLE
Make it possible to launch app with no user data

### ISSUE THREAD

**Issue by tscheepers** [moredip/Frank#141]
Could you make it possible to launch an app without any user data. My app, for example, remembers the users login state when the app quits. So I can't always execute all my tests without me constantly deleting the app in the simulator.

Perhaps you could add a method to the FrankHelper class? So you would be able to implement the following step:

```
Given /^I launch the app with an empty database$/ do
    # latest sdk and iphone by default
    launch_clean_app app_path
end
```

**Comment by chouti** [comment]
I've found there was one core step

``` ruby
When /^I reset the simulator/ do
  simulator_reset_data
end
```

Maybe this fits your need?
