### ISSUE TITLE
Can't inspect the UIAlertView using frank-cucumber 1.1.0

### ISSUE THREAD

**Issue by wittles2324** [moredip/Frank#143]
I have a login screen, after login successful to the system I use UIAlertView to show the message, when using frank-cucumber to inspect my app, I don't see UIAlertView element in ACCESSIBLE ELEMENTS (localhost:37265), other elements are shown in the Accessible Elements. How to write the step to touch UIAlertView button?

**Comment by moredip** [comment]
Hi Phat-Le,

Please ask about this on the [frank mailing list](https://groups.google.com/forum/?fromgroups#!forum/frank-discuss) - you're much more likely to get a response over there.

Cheers,
Pete
