### ISSUE TITLE
Frank's Lumberjack library interferes with the test project's Lumberjack library

### ISSUE THREAD

**Issue by jkubicek** [moredip/Frank#156]
If the test target has the Lumberjack logging library installed, `frank build` will fail with duplicate symbol errors. 

```
Ld Frank/frankified_build/./app.app/app normal i386
duplicate symbol _OBJC_IVAR_$_DDASLLogger.client in:
<dir>/Frank/libCocoaHTTPServer.a(DDASLLogger.o)
<dir>/build/Debug-iphonesimulator/libMagic.a(DDASLLogger.o)
```

etc. for all the other Lumberjack DDLog classes.

I'm not sure what the solution is. I'd say the easiest would be to remove the Lumberjack library from Frank release builds. I'm open to any alternatives.

**Comment by jkubicek** [comment]
Alternate solution may be [remove the `-all-load`](http://binaryfinery.wordpress.com/2010/06/11/universal-static-library-problem-in-iphone-sdk/) linker flag.

**Comment by jkubicek** [comment]
And it's actually CocoaHTTPServer that has the Lumberjack classes.

**Comment by frosty** [comment]
I'm seeing this same issue too - I'd like to use Lumberjack in my project, but Frank interferes with it.

**Comment by Guru-BetaTest** [comment]
Yes, I had this issue in past, I did rebuild the symbol names in Lumberjack which I thought would fix this issue.
It did fix the issue but maybe not a very good solution.
But when I frankify the other projects without Lumberjack, I saw build failures.

Thanks for fixing this.

**Comment by Guru-BetaTest** [comment]
Why am i still seeing this in open issue? is it not yet fixed?

**Comment by moredip** [comment]
You're right, this should now be fixed.

**Comment by chouti** [comment]
I'm using frank-cucumber gem version 1.1.10 and with -all-load flag open in my config file, but I will saw the duplicate error when building.

**Comment by jkubicek** [comment]
Same here, I'm still having issues with Lumberjack.

**Comment by jkubicek** [comment]
Here we go, need to use the proper flag

```
frank setup --without-cocoa-lumberjack
```

The rest of the flags are [here](https://github.com/drodriguez/Frank/blob/00f932bae42fdc6d9acea666865b696d467836d7/gem/lib/frank-cucumber/cli.rb).
