### ISSUE TITLE
frank_helper.rb's touch() method doesn't return an array like the documentation claims

### ISSUE THREAD

**Issue by akikoskinen** [moredip/Frank#166]
The documentation for the [touch method](https://github.com/moredip/Frank/blob/master/gem/lib/frank-cucumber/frank_helper.rb#L84) in `frank_helper.rb` says:

```
[ -- ]You can discover which of the matching views were actually
touched by inspecting the Array which is returned. [ -- ]
@return [Array<Boolean>] an array indicating for each view which
matched the selector whether it was touched or not.
```

In reality this method always returns `nil` (unless it raises an exception).

The last line of the method should probably read `touch_successes`.

**Comment by moredip** [comment]
Thanks for reporting this. Fixed as of 590b866b2ae42aa17a06ead779bc0129101c4d6e.
