### ISSUE TITLE
shelley could support view taged:123?

### ISSUE THREAD

**Issue by shoucal** [moredip/Frank#170]
is that anyway for me to write cases not by view marked? some of the view don't have accessed label, any way to query the view by tag?
that will be greate if it could

**Comment by moredip** [comment]
If you have to then you can definitely select by tag. Something like this would work I believe:

view tag:123

Cheers,

## Pete

Typed on a little bitty keyboard

**Comment by shoucal** [comment]
that will be great,thanks.

**Comment by brendensuarez** [comment]
`view tag:0` selects nothing even though there are plenty of views with tag set to 0. Any ideas?
