### ISSUE TITLE
type_into_keyboard bugs

### ISSUE THREAD

**Issue by shusson** [moredip/Frank#173]
We currently have frank server crashes when entering uppercase characters and periods using the helper type_into_keyboard. Could this be confirmed and/or fixed?

update: It also crashes if the textfield receiving the input reaches its end of line

env:
iOS6
iPad
frank 1.1.8

Thanks,
Shane

**Comment by moredip** [comment]
This should have been fixed as of 1.1.12, which includes 51bcffd190f3236d0a05b95de25418d43cf42cac
