### ISSUE TITLE
touch with UIAlertViewButton on landscape not works

### ISSUE THREAD

**Issue by mhaleem** [moredip/Frank#175]
Hello,

Frank seems to have a problem with "UIAlertView" when orientation is "Landscape", frank inspect also not working, when using dom dumping to check actual values i found that the whole calculations for "UIAlertView" and "UIAlerrtViewButton" not correct at all.

so using touch with "UIAlertViewButton" in Landscape orientation not working at all, currently i used fixed x,y to work around the problem with checking the orientation.

frank-cucumber (1.1.6)

**Comment by moredip** [comment]
Can you add a failing test to the Controls example app in the repo which shows this issue? It will make it easier for someone to work on and fix.

**Comment by mhaleem** [comment]
Hello, am trying to commit the changes to a new branch but i got permission denied so actually my test was  

Then I touch alert button "Button1"

and the step defintion 

Then /^I touch alert button "(.*?)"$/ do |label|
  selector = %Q|view:'UIAlertButton' marked:'#{label}|
  touch(selector)
end

In Landscape it fail to touch the button and not display an error .

**Comment by moredip** [comment]
This should now be fixed, as of gem version 1.1.10 which I just released. 

@mhaleem, it would be very helpful if you could confirm that 1.1.10 fixes this.

**Comment by mhaleem** [comment]
i have verified the solution in version 1.1.10 and it works great. thank you very much.
