### ISSUE TITLE
There is no support in the selector engine for UICollectionView

### ISSUE THREAD

**Issue by TimothyChilvers** [moredip/Frank#178]
Selectors such as "view:'UICollectionViewCell' first" don't work as expected - It selects an arbitrary cell rather than the first one.

**Comment by moredip** [comment]
This is a pretty hard one to fix I'm afraid. The ordering is based on the order of the subviews in the live view hierarchy, and that ordering appears to be quite arbitrary (presumably there are performance reasons for this). 

It's conceivable that we could re-arrange the reported order based on the view's location in the UI, but I don't see one general heuristic that could be used to decide that ordering.

**Comment by ondrejhanslik** [comment]
The same thing can happen with <i>UITableView</i> when cells are dynamically added/removed. It can also happen with plain <i>UIScrollView</i> - I saw it changing the order of its subviews in some cases (optimization?).

The best solution would be to add "sort" predicates to the query language. Sorting by position seems to be the best sorting option here (UIAutomation does it too).

Actually I am doing it in my frank tests - get all the cells (using "index"), sort them by accessibilityRect and then return the cell at the given position.

A much bigger problem is to get the text in table section headers. It requires some magic to check if the returned labels are not inside a cell.

**Comment by shoucal** [comment]
I am having the same problem too.  
is anyone could tell me how to execrate the function which  already write in my app?

such as I write a function  - (void) clickTableViews
how I could call it by frank?

thanks a lot.
-chao

## 

chao xu
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by ondrejhanslik** [comment]
You can use `frankly_map` for this. See core_frank_steps.rb for examples or just go for the documentation. It's very straightforward, e.g. `frankly_map(selector, "clickTableViews")`.

**Comment by moredip** [comment]
I'm going to close this issue out. I don't see a way to order the views that will always yield the 'correct' order.
