### ISSUE TITLE
Frank doesn't work with tmux

### ISSUE THREAD

**Issue by x1024** [moredip/Frank#179]
I had this exact issue today:
https://github.com/phonegap/ios-sim/issues/21

Removing tmux fixed the problem, but it took me more than an hour to find this issue (i had to go through frank, then sim_launcher, then finally ios-sim to get to it).

I suggest that a "Toubleshooting" section be added to the README, addressing this issue.

**Comment by moredip** [comment]
Can you add an entry to the README, or even better to the website's FAQ page: https://github.com/TestingWithFrank/testingwithfrank.github.com/blob/master/faq.md
