### ISSUE TITLE
Will Frank support Web View

### ISSUE THREAD

**Issue by santhanakrishnan** [moredip/Frank#181]
Hi,

Will frank support Web View API's

**Comment by Kishandewangan** [comment]
I am too interested in this, How we can automate the App testing which includes as Web view into it.

**Comment by moredip** [comment]
There's an entry in the [FAQ](http://testingwithfrank.com/faq) about this:

### Can I use Frank to test web-based apps?

If you want to test a pure web app (no native code at all) then Frank can’t help you, but the WebDriver project’s iPhoneDriver is a good option. If you have a hybrid app (a Native app which uses web views to implement some of the UI) then Frank does have some functionality to inspect the state of a web view, and evaluate javacript, but it’s fairly basic for now.
