### ISSUE TITLE
How to Integrate Frank with Victor

### ISSUE THREAD

**Issue by santhanakrishnan** [moredip/Frank#182]
Hi All,

Please get us know on "How to Integrate Frank with Victor"

**Comment by dhemery** [comment]
This is more of a Victor question than a Frank question.  I wrote Victor.  Check out the [Victor wiki](https://github.com/dhemery/victor/wiki).  If that doesn't answer your questions, [open an issue over there](https://github.com/dhemery/victor/issues).  Note:  The "how to configure Victor" documentation is currently out of date.  I'll fix that over the next week or so.

**Comment by santhanakrishnan** [comment]
Thanks Dhemery
