### ISSUE TITLE
Problems when setting up Frank in the iOS project.

### ISSUE THREAD

**Issue by r3econ** [moredip/Frank#186]
I have a problem with setting up Frank in my iOS project. I am following the instructions and executing in the console:

``` bash
sudo gem install frank-cucumber -V
```

What I get is:

``` bash
 ERROR:  Error installing frank-cucumber:
         activesupport requires i18n (= 0.6.1, runtime)
```

I have no idea what may be wrong. I checked the gems using:

``` bash
gem list --local 
```

and got:

``` bash
i18n (0.6.4)
```

Do you know what may be wrong? Thanks for every answer!

**Comment by moredip** [comment]
This is a ruby gems issue, not a Frank issue. However if you ask on the [frank mailing list](frank-discuss.googlegroups.com) you might find someone who can help.
