### ISSUE TITLE
Can't tap buttons

### ISSUE THREAD

**Issue by ckoehler** [moredip/Frank#2]
Hi,

First of all thanks for making Frank! It's awesome to use Cucumber for an iOS app!

I tried running the example project's features, and also implemented it into my own project, but for some reason the feature cannot push a button, in this case "Save." I looked through the code a bit, saw that it uses the accessibilityLabel and tried to set one explicitly, but no luck.

Additionally, it complained about not finding the method `red` on Object, so I guess the color_helper isn't included properly.

All this is on iOS 4.2, Frank checked out from GitHub today. I also ran the svn updater for uispec, which seemed to have run fine.

I appreciate any help!

Christoph

**Comment by moredip** [comment]
Hi Christoph,

It could well be that you don't have accessibility turned on either on your host machine or n the simulator. To turn it on in your host machine go to System Preferences, select Universal Access, and check "Enable access for assistive devices". To turn it on in the simulator, launch the simulator, launch the settings app, select General, select Accessibility, and then switch the Accessibility Inspector to On.

The reason for all this is I believe iOS won't expose accessibility labels unless you have the Accessibility Inspector turned on. Please let me know whether this helps resolve your issue.

As to your issues with color_helper, I'll try and reproduce here. They could well be broken.

**Comment by ckoehler** [comment]
Pete,

Thanks, that was it. Could you add that to the docs somewhere, just in case someone else comes across that? I guess it's not strictly a Frank issue, but it would be helpful.

Thanks for looking into the color_helper; I am sure a require somewhere would fix it, I just haven't spent too much time on it.

Thanks again!

Christoph

**Comment by moredip** [comment]
Glad to hear the accessibility thing was the issue. You're right, I should make the requirements for the accessibility stuff clearer.

Can you file a separate issue for the color_helper thing (with a stack trace too if possible)?
