### ISSUE TITLE
type_into_keyboard fails when keyboard is set to uppercase but the typed text starts with lowercase

### ISSUE THREAD

**Issue by ondrejhanslik** [moredip/Frank#202]
This is a minor issue with an easy workaround but it's still a bug.

When using `type_into_keyboard` with a lowercase text, e.g. `test` in a text field which capitalizes the first character, nothing is typed. The bug is caused by the fact that the keyboard is initially in uppercase mode and the lowercase letters are not searched.

The obvious workaround is to change the typed string to `Test`.

**Comment by CMTaylor** [comment]
Some text fields expect a capitalized first letter, but allow a lower case first letter.  In such a situation, type_into_keyboard should have some way to press the SHIFT key, as a user would, to turn of the uppercase mode and allow lowercase text entry.

**Comment by ondrejhanslik** [comment]
Just noticed there is already a test for this issue - `data_entry.feature` in the "Controls" example app.

**Comment by moredip** [comment]
Yeah, this is a known problem. It was discussed on the mailing list but looks like it never had a GH issue filed.

I have a pending pull request that solves this in the upstream KIFTypist class: https://github.com/square/KIF/pull/207

I wouldn't be much work to apply the fix directly to [PublicAutomation's copy of KIFTypist](https://github.com/TestingWithFrank/PublicAutomation/blob/master/PublicAutomation/KIFTypist.m), I just haven't had a chance to do it myself yet.

**Comment by moredip** [comment]
This should be resolved as of 1.1.12. I pulled in the KIFTypist changes in 51bcffd190f3236d0a05b95de25418d43cf42cac
