### ISSUE TITLE
Create UISpec mirror 

### ISSUE THREAD

**Issue by moredip** [moredip/Frank#21]
**As a contributor to Frank
I would like an easy way to submit UISpec patches
So that I can improve Frank without delay!**

I'm thinking about starting up an unofficial UISpec mirror on github. We could create a frank_patches branch on that, and pull that into Frank on a regular basis. It would be trivial to keep the unofficial mirror up to date, and hopefully trivial to keep the frank_patches branch merged with the main mirror branch.

**Comment by foozmeat** [comment]
I would use this
