### ISSUE TITLE
http://www.testingwithfrank.com/ redirect loop

### ISSUE THREAD

**Issue by subocn** [moredip/Frank#219]
310 (net::ERR_TOO_MANY_REDIRECTS)

Please refer to Issue #107

**Comment by lpaulger** [comment]
+1

**Comment by moredip** [comment]
Apologies for this. We're having issues with the GitHub pages setup which we use to host the website. We're working to resolve it.

Cheers,

## Pete

Typed on a little bitty keyboard

**Comment by subocn** [comment]
Thank Pete.

Regards,
Bo

At 2013-05-23 00:01:33,"Pete Hodgson" notifications@github.com wrote:
Apologies for this. We're having issues with the GitHub pages setup which we use to host the website. We're working to resolve it.

Cheers,

## Pete

Typed on a little bitty keyboard

On May 22, 2013, at 4:09 AM, Lucas Paulger notifications@github.com wrote:

> +1
> 
> ¡ª
> Reply to this email directly or view it on GitHub.

¡ª

**Comment by moredip** [comment]
www.testingwithfrank.com should be back up now, but we're still having DNS issues with testingwithfrank.com (without the www). Working to resolve it.

**Comment by moredip** [comment]
Should all be resolved now. May take a few hours for DNS changes to propagate.
