### ISSUE TITLE
iOS 7 - FEX_touchPoint not working

### ISSUE THREAD

**Issue by AutomationConsultant** [moredip/Frank#251]
I have upgraded my device to iOS 7 and observed that FEX_touchPoint does nt perform action on physical device. It works on simulator.

It seems blocker to run testcases on iOS7 device. Please, help me to find solution.

NV

**Comment by moredip** [comment]
Can you report this issue on the [Frank mailing list](http://groups.google.com/group/frank-discuss) - there are more folks on that list who will be able to help than there are watching these Github issues.
