### ISSUE TITLE
How to click a button on specify row of tableview ?

### ISSUE THREAD

**Issue by dangluan** [moredip/Frank#268]
I have many row on a table , and i want to click on a button on specify row of table
## smart phone  --------------------          edit  ---   delete

I want to click the edit button on clothes row of table.

**Comment by joemasilotti** [comment]
To click the 'sports' cell, try:

```
touch("tableViewCell marked:'sports' button marked:'edit'")
```

This will find the table cell with 'sports' in it's label(s), then in that
cell find a button that has a label with the text 'edit'. touch will, well,
touch that button.

**Comment by dangluan** [comment]
thanks man!
