### ISSUE TITLE
Add support for getting the view class name in Frank framework.

### ISSUE THREAD

**Issue by nacuteodor** [moredip/Frank#277]
Would it be possible to add support for getting the view class names as a String type using Frank ?
I would like to be able to use a code line like this: JSONArray matches=Frank.frankly_map(query,"getClassName");
I work with a java version of Frank. I am interested in being able to get the class list of the current app screen.

**Comment by oradyvan** [comment]
Have you tried this code?

```
frankly_map(query, "self")
```

**Comment by nacuteodor** [comment]
Yes, it works. I didn't know it exists that method. 
Thanks a lot!

**Comment by nacuteodor** [comment]
The support for view class name exists.

**Comment by nacuteodor** [comment]
Is there a way to see all the properties for a view? Also, could the app view tree be easily extracted?

**Comment by ondrejhanslik** [comment]
There is the dump method. Essentialy that's what symbiote is doing. Are you using symbiote?

**Comment by oradyvan** [comment]
Yes, as Ondrej said there is dump method available either as a call to function `frankly_dump` or as a URL `http://localhost:37265/dump`

Sometimes, this is even useful to get all the windows of the app with the method `http://localhost:37265/dump/allwindows`

**Comment by nacuteodor** [comment]
Yes, I use symbiote. I think http://localhost:37265/dump/allwindows is extactly what I want. 
Thanks a lot for sharing this info. I was thinking of a test tool that could be created keeping a good state of the app and then comparing the next modified app state, for regression testing.
