### ISSUE TITLE
Can I run Frank in Real Device

### ISSUE THREAD

**Issue by sougatabh** [moredip/Frank#28]
Is it is possible to run in real device, I tried in my IPad but it is failing, the server is not running.

**Comment by ma11hew28** [comment]
You can run UIAutomation on a real device, and iOS 5 even let's you record test cases, like Selenium IDE.

Matt

**Comment by moredip** [comment]
Yes, it is possible to run Frank on a real device. In fact, there's a discussion on the mailing list today about that: http://groups.google.com/group/frank-discuss/browse_frm/thread/d3c09addbccd861a. 

You'll probably want to use the experimental 'bonjour' branch on this repo. Feel free to ask on the list for more details.
