### ISSUE TITLE
Then /^I wait to not see a navigation bar titled "([^\"]*)"$/

### ISSUE THREAD

**Issue by olgagalchenko** [moredip/Frank#30]
Heyo,

When my app goes to a particular view it is supposed to hide the nav bar and reappear when the view is tapped. This works, but I'm trying to write an acceptance test for it now. Using "Then /^I wait to not see a navigation bar titled "([^\"]*)"$/" seemed perfect until it didn't work. I get "execution expired (Timeout::Error)" even though I can see that on the simulator the navigation bar hides itself after 3 seconds.

I am pretty clueless about Ruby, but this is the definition that I see in my core_frank_steps.rb:

Then /^I wait to not see a navigation bar titled "([^\"]*)"$/ do |expected_mark|
    Timeout::timeout(30) do
      values = frankly_map( 'navigationItemView', 'accessibilityLabel' )
      while values.include?(expected_mark)
        values = frankly_map( 'navigationItemView', 'accessibilityLabel' )
        sleep 0.1
      end
    end
end

Any ideas?

**Comment by moredip** [comment]
It could be that Frank isn't aware that the navigation bar is hidden. Normally we use the nav bar title steps just to check that we're on the right screen, not whether the view is hidden.
