### ISSUE TITLE
FrankServer.h  header not found

### ISSUE THREAD

**Issue by gaziebasha** [moredip/Frank#33]
Hi,  
I have followed the Frank tutorial for my project. When  I have done the step which is about modifying main.m.  It gives the error that FrankServer.h header not found. This error comes even in compile time.  If any body struggled with simillar kind of error please let me know the solution.

thanks

**Comment by moredip** [comment]
If you follow the newer approach that is available for XCode 4 (described on the wiki here - https://github.com/moredip/Frank/wiki/Frankifying-your-app-in-XCode-4) then you shouldn't run into this issue.
