### ISSUE TITLE
Support directly automating the keyboard

### ISSUE THREAD

**Issue by moredip** [moredip/Frank#34]
Frank doesn't allow you to directly manipulate the keyboard, which would be useful when doing things like editing text fields. just using methods like setText doesn't fire the same sequence of events, resigning first responder etc. which leads to lots of confusion on the mailing list and hacky work-arounds.

**Comment by alder** [comment]
Hi, Pete. I've created pullrequest that resolve this issue for me (and I think for all others) - #79

**Comment by moredip** [comment]
Sorta solved by pull request #79
