### ISSUE TITLE
color_helper methods not found

### ISSUE THREAD

**Issue by ckoehler** [moredip/Frank#4]
Hi,

Not much of a stacktrace, but I get:
    And I touch "Save"                        # Frank/cucumber/frankly_steps.rb:113
      undefined method `red' for #<Object:0x80b4c2f8> (NoMethodError)
      ./Frank/cucumber/frankly_steps.rb:117:in`/^I touch "([^\"]*)"$/'
      features/main.feature:11:in `And I touch "Save"'

My guess is the file isn't found, because I can change the helper to extend the String class with methods that definitely work in other apps I've written, and it still can't find it.

**Comment by moredip** [comment]
You can fix this by requiring color_helper.rb in your support/env.rb file (same way as you require in frank_helper.rb), but I should make it work by default. Thanks for the stacktrace.

**Comment by ckoehler** [comment]
I tried that, but it doesn't seem to work. When you define a module, do the methods automatically get added to Object? Or do you have to do `def Object` and extend it? 

Just wondering, but it may just be me, too.

**Comment by moredip** [comment]
Ah sorry, you'll also need to add a 
    World(ColorHelper)
call to your env.rb in order to get the methods in the ColorHelper module available when cuke is running.

**Comment by ckoehler** [comment]
Right on.
Incidentally, with the red() method, all I see in red is [FAIL, with the rest being in white. Without it, the whole error is already red. May be my local setup, but looks like this isn't always needed.
Just a minor thing though. Thanks!
