### ISSUE TITLE
UISwitch has stopped working

### ISSUE THREAD

**Issue by dlongmuir** [moredip/Frank#42]
If I run my iPad app using the 3.2 simulator the UISwitch code works but if I run it under 4.3 it doesn't flip it. I haven't had any time to investigate, I just run the Frank tests under the 3.2 simulator, i.e. 
simulator = SimLauncher::DirectClient.for_ipad_app( app_path, "3.2" )

The step I'm using is: 
  When I flip switch "switchName"

Maybe there is something in the Frank copy of UISpec that needs to be updated for 4?

**Comment by KingOfBrian** [comment]
Anyone else noticing this with 5.1?  Works on 4.3, not working for me on 5.1 though.  tap seems to get into KIF correctly, but nothing happens

**Comment by moredip** [comment]
the better swipe support in the latest KIF code fixes this AFAIK
