### ISSUE TITLE
Allow including custom helpers into the World

### ISSUE THREAD

**Issue by coffeencoke** [moredip/Frank#51]
I would like the ability to do something like this in my env.rb:

```
Dir[File.join(File.dirname(__FILE__), 'helpers', "/*.rb")].each { |f| require f }
World(LaunchHelper)
```

So that I can include my own helpers.  If you would like to give me some direction on where to do this, I may be able to do it.

**Comment by moredip** [comment]
Any file that you add to the support directory should be evaulated by cucumber during startup. If you want to create your own helpers it should be as simple as just adding a launch_helper.rb file to that directory, and then adding the World(LaunchHelper) call to your env.rb.
