### ISSUE TITLE
Cannot flash GRPortalListItem in symbiote

### ISSUE THREAD

**Issue by nabsofken** [moredip/Frank#58]
I can flash any element that starts with UI but cannot flash elements that start with GR. How can I flash elements that start with GR.

Thanks

**Comment by moredip** [comment]
you can select views of a custom class using a selector this: `view:'GRPortalListItem'`

**Comment by nabsofken** [comment]
I am a little confused about the format.
For UI elements, for example UIImageView with identifier LogOn, I type 
imageView marked:'LogOn'
How would I write one for a custom class, for example GRReportListItem with identifier Logon?
Thanks

**Comment by moredip** [comment]
You would write something like `view:'GRReportListItem' marked:'Logon'`. There are some more details [here](http://code.google.com/p/uispec/wiki/Documentation) and [here](https://github.com/dhemery/victor/wiki/Queries:-Identifying-Views)
