### ISSUE TITLE
Swipe

### ISSUE THREAD

**Issue by cassied** [moredip/Frank#70]
Help!

I know that gestures are a new thing with Frank, but has anyone got them to actually work? I'm looking for swiping, in particular. I've got the standard swipe to the right/left to delete function going on in my app, and I want to test the swipe. Am I supposed to add anything special?  I've tried adding UISpec to my project, and am getting failed builds. GraphicsServices.framework added nicely, with no problems.

When I run cucumber, I get a passed when, but a failed then (which makes sense, since the delete button doesn't show up).

I'm pretty new to all of this, so take it easy on me. Any help is greatly appreciated! 

Thanks!
Cassie :)

**Comment by moredip** [comment]
Hi Cassie, can you post this on the [frank mailing list](http://groups.google.com/group/frank-discuss)? I think you'll get a better response there than from me :) I'm not using gestures with Frank.
