### ISSUE TITLE
Symbiote "flash" using any registered selector engine

### ISSUE THREAD

**Issue by dhemery** [moredip/Frank#72]
Symbiote's "flash" feature is very handy for testing and diagnosing selectors. Currently, the feature works with only the two built-in selector engines, uiquery and shelley_compat.

Please allow Symbiote to use any registered selector engine. Perhaps display a select element with the engines as options.

This feature would be very useful for me, given that I often use an alternative selector engine (Igor).

**Comment by moredip** [comment]
Plus one. 

I'd like to extend Symbiote's selector testing in a couple of directions:
a) choose which engine to use (shelley, igor, etc)
b) choose which operation to perform on views which match the selector (flash, touch, etc).

**Comment by moredip** [comment]
This is implemented as of 9a2366b, courtesy of @kingofbrian

**Comment by dhemery** [comment]
Hi Pete,

I finally got around to trying this. Awesome!

Thanks,
Dale
