### ISSUE TITLE
Symbiote does not load

### ISSUE THREAD

**Issue by mung-thai-dev** [moredip/Frank#83]
Hi,

I am having issue of Symbiote does not load, the refresh icon keep spinning.

I am using Frank 0.8.8 with IUQuery

run http://<ip add>:37265/map, getting error: {"details":"**\* -[NSPlaceholderMutableString initWithString:]: nil argument","outcome":"ERROR","reason":"invalid selector"}

Thanks for helping.
Mung

**Comment by moredip** [comment]
Did you get this resolved? If not let me know and I'll try and figure out how to reproduce the problem locally.
