### ISSUE TITLE
Symbiote: Allow left and right sections to scroll independently

### ISSUE THREAD

**Issue by dhemery** [moredip/Frank#91]
When the view hierarchy is long (takes up a lot of vertical space), scrolling down the hierarchy scrolls the whole page, so that the simulator image is scrolled out of view.

Proposal: Allow the left and right sections of the Symbiote view (the list tabs and the inspect tabs) to scroll independently.

**Comment by CMTaylor** [comment]
It would also be nice if the screenshot view was rotated to the appropriate orientation (as provided by the device/simulator) and, for iPad, shrunk to a smaller size so as not to use up too much horizontal screen real estate.

**Comment by moredip** [comment]
This was resolved a while ago.
