### ISSUE TITLE
Expose KIF's keyboard driver

### ISSUE THREAD

**Issue by moredip** [moredip/Frank#93]
As a test engineer
I would like to be able to tell Frank to simulate pressing keys on the keyboard
So that I can more accurately simulate user interactions with my app

See discussion in https://groups.google.com/d/topic/frank-discuss/eHi4jTHi5Vg/discussion for more details

**Comment by soonernotfaster** [comment]
May I ask why? Frank already allows the simulation of text input. What are you looking to get out of having the keyboard being displayed? ( said with a tone of curiosity ) 

Thanks
Steven Solomon

**Comment by moredip** [comment]
Hey @steven-solomon, I'm sort of parrotting the Frank mailing list, but the main reasons were that it's hard to ensure your tests are going through all the same intricate dances with the Cocoa API as your production code does if you're doing things like setting text in an edit box directly. By driving the keyboard we get closer to the way a real user interacts with the app, and thus the tests have less weird behavior

**Comment by moredip** [comment]
Done as of e13f8eb5fd4ded32bee05cf1f94056c5e257bfa8
